# Generated by Django 5.0.6 on 2024-05-17 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
                ('computingID', models.TextField()),
                ('dateLogged', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
